// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpscqdymyxxypybcrwyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwc2NxZHlteXh4eXB5YmNyd3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDkwMjEsImV4cCI6MjA2ODQyNTAyMX0.TLLWEoyhWgIWhtBpCZw7o6vvkcavTByx41F8wJEA80g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});