// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnrcgzyvczxsevwolxkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducmNnenl2Y3p4c2V2d29seGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzI4OTAsImV4cCI6MjA2ODg0ODg5MH0.vCahs8l9Vdh_NNxi6RxuM1B9mhlBi-6q3kI8_gdSErc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});